### ISSUE TITLE
Thread-safety problems with LazyList

### ISSUE THREAD

**Issue by kaaku** [viritin/viritin#136]
When using a combination of (M)Grid, ListContainer and LazyList, the lazy loading in the LazyList can take an awful long time in certain cases. This seems to be caused by a race condition inside LazyList, where multiple threads invoke the methods `get()`, `indexOf()` and/or `contains()` simultaneously. I'm not familiar enough with Vaadin internals to be able to say why this happens. The problem can be observed e.g. by putting a breakpoint in `get()` and then scrolling the Grid (by a big leap) via the user interface. When stepping through the method execution with the debugger, you'll see that the lists `currentPage`, `prevPage` and `nextPage` (which hold the pages currently cached by the list) get reassigned sporadically during the method's execution, indicating a threading problem. LazyList should probably be thread-safe to prevent this (at least in the described use case).

Here is a simple [example project](https://github.com/viritin/viritin/files/121417/threading.zip) based on the Vaadin Maven archetype that demonstrates the problem. It creates an MGrid + ListContainer + LazyList combination, and mocks the database with a PagingProvider that generates entities on request. If you run the app, open the page in your browser, and then e.g. scroll down to around halfway down the list by dragging the scrollbar quickly with your mouse, the load time should become quite long (several seconds at least). Take a look at the logs; the app logs all page requests received by the PagingProvider. In my testing, this simple scrolling resulted in hundreds, or even over a thousand page fetches. You'll also see that it keeps fetching the same 3 adjacent pages over and over again, apparently until the race condition happens to get resolved (lucky timing?).

The example app also contains an alternative lazy-loading list implementation, PersistentLazyList, which I wrote as a replacement to LazyList in my current project once I noticed the described problem. You can enable it in the example app by toggling the line comments in MyUI. It has two key differences to LazyList: it's thread-safe; and it doesn't throw away old pages automatically, but holds on to them (hence the 'persistent'). The latter property might not be desirable in all cases, but in my current project it is, as the database is currently our bottleneck, and reducing its load is key. In any case, I think it's a good alternative to LazyList for certain use cases. If you're interested, I can make a pull request that contains it (and unit tests). I haven't touched LazyList, though, so the problem described above still exists.

**Comment by mstahv** [comment]
Hi,

I'll need to check out your project and play with it a bit when I find a moment (I'm traveling still this week). I guess Grid makes such a seek into the data the that to current LazyList hasn't prepared for that. With MTable, which I have used quite a lot more, this hasn't been an issue.

Your PersistenLazyList looks like a decent approach, and it is actually quite similar that I first drafted for LazyList. But, if I read the code right, that indeed is not desirable if you have a huge dataset and  users tend to scroll through the whole dataset -> the data is never GC:d. But in practice that is rarely the case, so this might be excellent alternative at least if the more memory savvy solution don't work.

Feel free to post the pull request. Also, if you can post your quality test case into src/test/java/../it/,it  would help testing and debugging. 

cheers,
matti

**Comment by mstahv** [comment]
Hi, I checked out the project and played with it a bit. Looks like Grid is making such indexed seeks into the List that its fuzzy logic don't work anymore and it needs to do lots of looping.

As a workaround you can you a larger pagesize for lazy list. I randomly tried 200 for your test app and the issues where gone, even though I increased the latency simulation to 400ms.

The perfect page size depends on the size of the grid and theme. It would be really nice if we could control the amount that rows that Grid caches. In Table we had a configuration option for this but I'm not aware of such for Grid. @tsuoanttila , I think I just asked the same recently regarding an other issue. Would it be hard to add such a parameter? To me the currently used amount of "reserve data" is quite large.

@kaaku, although this isn't probably a thread safety issue or anything else we can fix, don't close the issue. This definitely needs to be outlined in Viritin documentation (that I plan to start writing soon). Let's keep this open until that is done.

**Comment by mstahv** [comment]
Got an idea, maybe the LazyList should be more configurable, bit more like the version from @kaaku, but still a one that do GC the stuff afterwards. We could then let the developer decide, how many "pages" the LazyList keeps in cache. Now it is hard coded into three.

@kaaku want to try working on this?

If it would be really smart, it would figure out a proper amount by the calls that Grid/Table does to it, but this would be rather hacky solution.

**Comment by kaaku** [comment]
I actually considered making the list more configurable as you suggested, at least adding the ability to control the amount of cached pages. But as I was under a really tight schedule, I implemented the PersistentLazyList as it was a lot simpler. It would be interesting to try to combine these two approaches into one implementation, I could try to do that when I have more time. Adjusting the page size automatically based on the received requests would be great, but that would require understanding the use cases pretty well. I'm quite new to Vaadin and have only used the Grid, so I'll probably leave that for someone else. Doing that would also require a change in the PagingProvider interface, as it would need to be able to control the range of rows that is fetched (currently it only gets the start row as an argument). Doing that might be a good idea in any case, as it would improve performance if the list could fetch multiple pages in one go if `getItemIds(int, int)` is invoked with a range that's larger than one page. E.g. in the example app the Grid requests around 200 rows at a time, so the list should be allowed to fetch that many rows with one database query even if the user had set the page size to be 100. What do you think?

**Comment by mstahv** [comment]
A new version of LazyList is not in git. I hope you can test it, but I'm pretty confident about the solution. The amount of required cached pages is not determined on the fly, based on subList calls that Grid use. I'll look into some other issues still for a short while and then make a build.

The amount of cache that Grid uses is rather large :-( I hope there would be an API to limit that.
